require:
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 3.4.7
  Exclude:
  - vendor/bundle/**/*
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Style/ClassVars:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
  Max: 25
Layout/EndOfLine:
  EnforcedStyle: lf
